
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 21 05:14:07 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 10;
  public static final int INCREMENT = 24;
  public static final int CONST = 5;
  public static final int ASSIGNMENT = 23;
  public static final int NOT_EQUAL = 42;
  public static final int GREATER = 37;
  public static final int CONTINUE = 35;
  public static final int NUM_CONST = 9;
  public static final int MINUS = 15;
  public static final int DECREMENT = 25;
  public static final int SEMICOLON = 26;
  public static final int AND = 12;
  public static final int OR = 13;
  public static final int COMMA = 27;
  public static final int LEFT_BRACE = 19;
  public static final int RIGHT_PARENTHESIS = 29;
  public static final int LESSER = 39;
  public static final int PLUS = 14;
  public static final int IF = 30;
  public static final int EOF = 0;
  public static final int RETURN = 36;
  public static final int EQUAL = 38;
  public static final int GREATER_EQUAL = 40;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MODULO = 18;
  public static final int RIGHT_BRACE = 20;
  public static final int BREAK = 34;
  public static final int IDENT = 8;
  public static final int VOID = 6;
  public static final int LEFT_SQUARE = 21;
  public static final int ELSE = 31;
  public static final int READ = 4;
  public static final int WHILE = 33;
  public static final int LESSER_EQUAL = 41;
  public static final int RIGHT_SQUARE = 22;
  public static final int BOOL_CONST = 11;
  public static final int DIVISION = 17;
  public static final int MULTIPLICATION = 16;
  public static final int PRINT = 3;
  public static final int LEFT_PARENTHESIS = 28;
  public static final int DO = 32;
}

